services:
  web:
    image: jerrylinsga/sga-winter-camp:latest
    container_name: sga-winter-camp
    restart: always
    ports:
      - "1212:3000"
    volumes:
      - ./db.json:/app/db.json
    environment:
      - NODE_ENV=production
